name = "PointProcesses"
uuid = "b182abae-5f4f-4b13-afa8-f0ca325f1568"
authors = ["jkling <jose.kling@pm.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
